wrapper:
  data_reader:
    class_path: _3_data_management._3_1_data_readers.SPD_matrices_from_EEG_signals.SPDFromEEGDataReader.SPDFromEEGDataReader
    init_args:
      preprocessing_config_file: SPD_matrices_from_EEG_MASS_SS3_dataset_EUSIPCO_signals_config.yaml